### ISSUE TITLE
[Feature Request] Publish mac ARM64 binary 

### ISSUE THREAD

**Issue by charlesoconor** [hadolint/hadolint#1004]
- [ ] This is a bug report
- [x] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior

It would be very nice if the arm 64 mac binary was published along with the the other ones published on release. M1 Macs are becoming more and more common. I've built the binary locally without modification on my machine. 

I don't know how cross-compiling works in Haskel, so it might be complicated if there aren't arm64 runners that can be pulled.  

**Additional environment details (OS, stack version, etc.)**
OS: OSX ARM64

**Comment by eread** [comment]
@charlesoconor This issue is probably a duplicate of: https://github.com/hadolint/hadolint/issues/842.

**Comment by charlesoconor** [comment]
Closing as dup.
