### ISSUE TITLE
hadolint being flagged as malware by SentinelOne

### ISSUE THREAD

**Issue by ThomasWunderlich** [hadolint/hadolint#1036]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

This is primarily a tracking ticket for a potential malware issue, although its likely a false positive.

### Expected behavior
hadolint is installed and not flagged as malware

### Actual behavior
hadolint is installed and is detected as malware and quarantined

### Steps to reproduce the behavior
On a mac with SentinelOne installed, install hadolint. It will be marked as malware and be quarantined.

Version: 2.12.0

This affects hadolint installed via asdf. I'm testing alternate install methods now

**Output of `hadolint --version` or
  `docker run --rm hadolint/hadolint hadolint --version` or
  `docker run --rm ghcr.io/hadolint/hadolint hadolint --version`:**

```bash
(paste your output here)
```

**Dockerfile** (if relevant)

```Dockerfile
(paste content of your Dockerfile)
```

**Additional environment details (OS, stack version, etc.)**

**Comment by ThomasWunderlich** [comment]
Closing. This appears to be a sentinelone ML false positive. This was only triggered when installed via asdf, installing the same version via homebrew didn't trigger SentinelOne

**Comment by yld** [comment]
You may reopen as it is also seen as malware when installed through Lazyvim and Mason

**Comment by skriems** [comment]
Half of my homebrew environment got put into quarantine now for the 3rd time by sentinel one. I don't know why it should be a problem of hadolint - just wanted to give my 2 cents.

**Comment by GeordieEK** [comment]
A re-open would be great! I am also having issues with hadolint being flagged as malicious when installed through Lazyvim & Mason.

**Comment by dennypenta** [comment]
how to fix on macos:
- let sentinel remove it or remove it using mason
- install it using brew
- enjoy
in my case mason has successfully discovered it and works well

**Comment by guest20** [comment]
Why are y'all reporting it here instead of reporting it to the AV as a false positive? 

https://sentinelone.com/faq/, look for "false positive" 

Also let your admins know that this "ai malware" is causing problems. And maybe consider not paying them anymore.

**Comment by br4mm** [comment]
> Why are y'all reporting it here instead of reporting it to the AV as a false positive?
> 
> https://sentinelone.com/faq/, look for "false positive"
> 
> Also let your admins know that this "ai malware" is causing problems. And maybe consider not paying them anymore.

If I were to maintain this product/project, I would like to be aware of these things and potentially do something about it pro-actively (hence the comment). If maintainers have a different opinion then that's fine too ofcourse.  As for me specifically, we've indeed muted this occurrence.
