### ISSUE TITLE
Moving to new org logicstics

### ISSUE THREAD

**Issue by lukasmartinelli** [hadolint/hadolint#120]
I moved hadolint under it's own org and gave admin rights to y'all.
This will help making shared ownership more transparent and help implementing things like #119.

Y'all should have all the powers to deal with the organization.
I need to figure out whether moving the repository broke anything.

<img width="473" alt="people_ _haskell_dockerfile_linter" src="https://user-images.githubusercontent.com/1288339/33298604-47b5d894-d3b5-11e7-99c9-924549d2fac0.png">

/cc @ye @backus @zemanlx @lorenzo

**Comment by zemanlx** [comment]
@lukasmartinelli I think that is a great step forward. Can you also move Docker Hub `lukasmartinelli/hadolint` into organisation `hadolint`?

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli I think that is a great step forward. Can you also move Docker Hub lukasmartinelli/hadolint into organisation hadolint?

Should have gotten access. I need the user names to add access to the dockerhub org who need it.

<img width="1052" alt="docker_hub" src="https://user-images.githubusercontent.com/1288339/33332425-3da4fd62-d432-11e7-9363-39ecc7965a73.png">

<img width="1037" alt="hadolint_hadolint_-_docker_hub" src="https://user-images.githubusercontent.com/1288339/33332852-54d84ff6-d433-11e7-8167-ff7aa8041a72.png">

**Comment by zemanlx** [comment]
I believe all is set up.

**Comment by lorenzo** [comment]
@zemanlx can you include me in the dockerhub team? My username there is `joselorenzo` not `lorenzo`

**Comment by zemanlx** [comment]
@lorenzo done
