### ISSUE TITLE
Update brew formula to use v1.2.3 of `hadolint`. 

### ISSUE THREAD

**Issue by zemanlx** [hadolint/hadolint#126]
- [x] This is a feature request
- [x] I searched existing issues before opening this one

Update brew [formula](http://formulae.brew.sh/formula/hadolint) to use v1.2.3 of `hadolint`.

**Comment by ilovezfs** [comment]
voilà https://github.com/Homebrew/homebrew-core/pull/21365

**Comment by zemanlx** [comment]
https://github.com/Homebrew/homebrew-core/pull/21365 merged.
