### ISSUE TITLE
[Bug] Break on comments inside dockerfile

### ISSUE THREAD

**Issue by Yivan** [hadolint/hadolint#146]
Hello

Thanks for this great tools and sharing it with us.

It seems to have problem with comment inside multiline apt-get.
If you try to validate this dockerfile (official mariadb):
https://raw.githubusercontent.com/docker-library/mariadb/506cd7c6b9d6c53d7b514a2c94db5d3daee832fd/10.3/Dockerfile

You will see hadolint cannot parse it and breaks.
Maybe comments should be automaticaly stripped out before analyse ? (removing the comment lines)

Thanks

**Comment by zemanlx** [comment]
Thank you @Yivan for reporting, we know that it is an issue. @lorenzo has done a great progress in our parser [language-docker](https://github.com/hadolint/language-docker) which is used in _hadolint_ and did a release today. I believe this issue disappear as soon as we use `language-docker-2.0.0`

@lorenzo do you plan to make a PR for that?

**Comment by lorenzo** [comment]
@zemanlx I tagged 2.0 today, will try sending a PR to this repo with the upgrade soon

**Comment by Yivan** [comment]
Thank you for you fast fix! All work nice now.
