### ISSUE TITLE
Tag hadolint docker image

### ISSUE THREAD

**Issue by ferrarimarco** [hadolint/hadolint#150]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior
Each hadolint release should produce a tagged image. Docker Hub can be configured to build such images automatically on each commit and each tag, as you know.

### Actual behavior

Docker images are not tagged. See https://hub.docker.com/r/lukasmartinelli/hadolint/tags/

### Steps to reproduce the behavior

N/A

**Comment by lorenzo** [comment]
@lukasmartinelli @zemanlx Can you guys grant me access to docker hub? I can set it up there

**Comment by zemanlx** [comment]
@ferrarimarco that is an old location for the hadolint image. All new releases/master are in https://hub.docker.com/r/hadolint/hadolint/tags/

**Comment by ferrarimarco** [comment]
Cool, I see... maybe you could add a warning in the description of the old one? Thanks!

**Comment by zemanlx** [comment]
@lukasmartinelli can you please add a warning in the description of https://hub.docker.com/r/lukasmartinelli/hadolint/ for users to use https://hub.docker.com/r/hadolint/hadolint/?

**Comment by zemanlx** [comment]
@lorenzo you should have full access to https://hub.docker.com/r/hadolint/hadolint/

**Comment by lorenzo** [comment]
Sweet, I guess this does not need any fixing :)
