### ISSUE TITLE
Publish hadolint-1.3.0 on hackage

### ISSUE THREAD

**Issue by mrueg** [hadolint/hadolint#160]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior
https://hackage.haskell.org/package/hadolint shows 1.3.0 as latest
### Actual behavior
https://hackage.haskell.org/package/hadolint still shows 1.2.6 as latest

**Comment by lorenzo** [comment]
Sorry I missed this. Thanks fro bringing it up, I just uploaded the new version
