### ISSUE TITLE
Disable rules with inline comments

### ISSUE THREAD

**Issue by lorenzo** [hadolint/hadolint#165]
Based on the ideas proposed [here](https://github.com/hadolint/hadolint/issues/74#issuecomment-367034282), Implement a system to ignore certain hadolint rules based on inline comments found in the dockerfile

**Comment by aw-was-here** [comment]
Re-reading, I feel like I wasn't very clear about the temporary part. :) The disabled rule is only disabled for that line. e.g.:

```
# hadolint disable=DLxxxx
RUN foo1
RUN foo2
```
DLxxxx is disabled for the foo1 line.  But if the foo2 line has the DLxxx issue, it would still throw an error.

Thanks!

**Comment by lorenzo** [comment]
Yeah, I understood that. Thanks for clarifying anyway!

**Comment by OdysLam** [comment]
For anyone who may stumble on this GitHub issue, the keyword is `ignore`, not `disable`.

**Comment by Hongbo-Miao** [comment]
Just add link to latest document for multiple ways: https://github.com/hadolint/hadolint#inline-ignores 😃
