### ISSUE TITLE
Crash on Linux with specific locale settings

### ISSUE THREAD

**Issue by IngoHeimbach** [hadolint/hadolint#173]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

When running with the following locale settings:
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=C
LC_TIME=en_US.UTF-8
LC_COLLATE=C
LC_MONETARY=C
LC_MESSAGES=en_US.UTF-8
LC_PAPER=de_DE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
hadolint crashes immediately with the error message:
```
 hadolint: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
```
If `LC_ALL` is set to `C` before, hadolint can be used as usual.
I use the latest version 1.5.0 on Debian buster. On macOS, hadolint works fine without setting `LC_ALL`.

**Comment by lorenzo** [comment]
I think this can be resolved by not statically linking against the libraries. I will remove the static linking in the next release.

**Comment by zemanlx** [comment]
@lorenzo if we remove static linking we will lose our minimal image (it won't run in busybox anymore). Is there any other option how to solve this?

**Comment by lorenzo** [comment]
I’m not sure that is true, but if it is, we can have different compilation options for the image and for the binaries we distribute.

**Comment by zemanlx** [comment]
I have tried dynamic a few _OS_ via docker image. If we build binary with dynamic linking we will need to ask users to install some prereq packages for some OS which is from my point of view a high price (sudo for install) in user comfort/automation. 

```bash
for i in debian:8 debian:9 ubuntu:14.04 ubuntu:16.04 centos:6 centos:7 fedora:26 fedora:27
do
  echo ">>> $i"
  docker run --rm -it -v /home/zeman/git/hadolint/.stack-work/install/x86_64-linux/lts-10.7/8.2.2/bin:/dynamic \
    $i ldd /dynamic/hadolint | grep "not found"
done
>>> debian:8
        libgmp.so.10 => not found
>>> debian:9
        libgmp.so.10 => not found
>>> ubuntu:14.04
        libgmp.so.10 => not found
>>> ubuntu:16.04
        libgmp.so.10 => not found
>>> centos:6
/dynamic/hadolint: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /dynamic/hadolint)
        libgmp.so.10 => not found
>>> centos:7
>>> fedora:26
>>> fedora:27
```

I would rather get this solved in a different way. I think that we should not give up static linking so easy.

**Comment by zemanlx** [comment]
@lorenzo Shouldn't we set `LC_ALL` (if it is `NULL`) to  `C.UTF-8` (debian world) or `C.utf8` (Red Hat world)  or fallback to safe `C` for hadolint? 

I think that https://hackage.haskell.org/package/setlocale-1.0.0.5 should do the trick.

**Comment by zemanlx** [comment]
or use stack [approach](https://github.com/commercialhaskell/stack/issues/856#issuecomment-135076052).

**Comment by lorenzo** [comment]
@zemanlx I think we should follow what stack does. It is a lot of code, though

**Comment by zemanlx** [comment]
@IngoHeimbach everything good comes in three and I believe that this issue is finally solved. Can you please confirm it?

**Comment by IngoHeimbach** [comment]
Great job, the latest version 1.7.1 works for me :+1:
