### ISSUE TITLE
Ability to enforce values for LABEL via hadolint

### ISSUE THREAD

**Issue by marccarre** [hadolint/hadolint#199]
[_This is a feature request, and I searched existing issues before opening this one._]

### Problem

In order to have better traceability of my container images, I'd like them to have various `LABEL`s on their `Dockerfile`s, e.g.:

- [`opencontainers`' `image-spec` labels](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys), or
- [`label-schema` labels](https://microbadger.com/labels), or
- any other arbitrary label.

As human beings are notoriously unreliable and undeterministic, I'd like a way to to enforce such labels across projects' `Dockerfile`s.

### Potential solution

Since `hadolint` is a linter for `Dockerfile`s, maybe this should be:

- where such rules about labels can be defined, and
- how they should be enforced.

Thoughts?
N.B.: I currently do know Haskell, but fwiw, I'd be happy to try to come up with a PR.

### Alternatives

- [`dockerfile-lint`](https://github.com/projectatomic/dockerfile_lint/blob/master/sample_rules/recommended_label_rules.yaml)
- [`dli`](https://github.com/garethr/docker-label-inspector) (thanks for [pointing this out](https://github.com/hadolint/hadolint/issues/199#issuecomment-388076703) @zemanlx)

**Comment by lorenzo** [comment]
How would you ideally express the labels requirement?

**Comment by marccarre** [comment]
I don't have a specific nor strong opinion on this right now, but would probably start with some form of label name - regex pair. Maybe these could be defined in a `.hadolintrc` file, either in JSON or YAML?
For example:

- JSON
  ```json
  {
    "LABEL": {
      "org.opencontainers.image.revision": {
        "valueRegex": "[0-9a-f]{7,40}"
      }
    }
  }
  ```

- YAML
  ```yaml
  LABEL:
   org.opencontainers.image.revision:
     valueRegex: [0-9a-f]{7,40}
  ```

**Comment by lorenzo** [comment]
I'm not really keen on adding regexes to this tool, they are very fragile. If that solution didn't exist in another tool, how else would you like to express it?

Can we maybe come up with a number of commonly used rules for labels? for example `valueRegex: [0-9a-f]{7,40}` looks like it could just be `short_sha || long_sha`

**Comment by lorenzo** [comment]
Another thought would be to use a DSL or any other intermediate language for expressing additional rules, but I'd like to explore simpler options first

**Comment by marccarre** [comment]
> I'm not really keen on adding regexes to this tool [...] Can we maybe come up with a number of commonly used rules for labels?

Sure, some "strong types" could be:
- `git_hash` for, e.g. `org.opencontainers.image.revision`
- [`semver`](https://semver.org/) for, e.g. `org.opencontainers.image.version`
- [`url`](https://tools.ietf.org/html/rfc1738) for, e.g.:
  - `org.opencontainers.image.url`, 
  - `org.opencontainers.image.documentation`, 
  - `org.opencontainers.image.source`.
- [`datetime`](https://tools.ietf.org/html/rfc3339#section-5.6) for, e.g. `org.opencontainers.image.created`
- [`license`](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60) for, e.g. `org.opencontainers.image.licenses`
- `string` for arbitrary, non-empty strings in, e.g.:
  - `org.opencontainers.image.title`
  - `org.opencontainers.image.description`
  - `org.opencontainers.image.authors`

**Comment by marccarre** [comment]
Indeed, @zemanlx, this could do the job :+1:

**Comment by nipuna-perera** [comment]
Any progress on this?

**Comment by SuperSandro2000** [comment]
@marccarre Don't you think you can incoperate docker label inspector into your CI workflow?

**Comment by lorenzo** [comment]
closing as there is a PR open
