### ISSUE TITLE
Code Climate Engine

### ISSUE THREAD

**Issue by devth** [hadolint/hadolint#20]
Would be useful to run `hadolint` as a Code Climate Engine:
http://blog.codeclimate.com/blog/2015/07/07/build-your-own-codeclimate-engine/

**Comment by lukasmartinelli** [comment]
- [ ] Need to trim down the image size from 1 GB to 250MB first (but that's a good thing anyway). Will probably create a special distribution file.
- [ ] Implement a JSON formatter

**Comment by lukasmartinelli** [comment]
Just remember that your initial suggestion was to use the API from the website.

 That will be much less work to integrate.

**Comment by devth** [comment]
I was actually thinking of running it as an engine, but API would be nice too.

The Yetibot plugin runs CodeClimate locally, so the only way it could take advantage of hadolint is if it were packaged as an engine.

**Comment by lukasmartinelli** [comment]
> The Yetibot plugin runs CodeClimate locally, so the only way it could take advantage of hadolint is if it were packaged as an engine.

Wuhuu. It is actually not that difficult to build a static Haskell binary (building it crossplatform is though).
I can now have build container that spits out the binary that I can then add to a blank image and stay under the 200MB limit. Should write a Makefile for that.

**Comment by devth** [comment]
Nice! I wonder if Travis or CircleCI or a similar could help with cross-platform builds?

https://circleci.com/docs/language-haskell

**Comment by lukasmartinelli** [comment]
Will take a bit longer. In order to make it work I need to implement #9 and #13 first - and file globbing as well.

First thought about just writing a wrapper script in a other language to simply transform the output into JSON and deal with all the other stuff - but that would be giving up on Haskell :grimacing:

> Nice! I wonder if Travis or CircleCI or a similar could help with cross-platform builds?

The only good crosscompile story I've seen so far is in Go. Haven't found something on the internet
to simply create binaries for OSX, Windows and Linux for Haskell on one single platform.
But you're right, I could just build a binary on the corresponding platform.

**Comment by devth** [comment]
I thought Docker would remove the need to cross-compile.

**Comment by dblandin** [comment]
Hey @devth @lukasmartinelli,

I'm Devon, an engineer at @codeclimate.

Awesome to see that you're considering hadolint for a Code Climate engine! We have a `Dockerfile` in nearly every codeclimate repo and would definitely benefit from this tool during our own analyses.

A colleague of mine and haskell enthusiast, @pbrisbin, recently dealt with the same issue regarding image size during the development of his [codeclimate-hlint][] engine. This [PR][] in particular might interest you.

Feel free to reach out to me or @mrb as codeclimate resources. I'm personally new to haskell but would love to dive in sometime and contribute.

[codeclimate-hlint]: https://github.com/pbrisbin/codeclimate-hlint
[PR]: https://github.com/pbrisbin/codeclimate-hlint/pull/8

**Comment by lorenzo** [comment]
@dblandin @mrb I added a flag to the binary to produce codeclimate json output. What's the next step to create an engine?

**Comment by pbrisbin** [comment]
Hi @lorenzo,

As an example, you can check out my PR to add CC engine support to HLint here: https://github.com/ndmitchell/hlint/pull/383. You've done the first part (e.g. `--json-cc`), the other step would be a specific Docker image to run it as an engine.

I no longer work at Code Climate but am happy to help, as I'd like to see this as an engine too. Also, if you sign up at https://codeclimate.com/dev_form/, you will be invited to the community slack channel where we can all chat about this a little more synchronously.
