### ISSUE TITLE
Error when parsing FROM with sha256 hash

### ISSUE THREAD

**Issue by timbru31** [hadolint/hadolint#263]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior

hadolint should be able to proceed linting.

### Actual behavior

hadolint crashes.

### Steps to reproduce the behavior

1. Lint Dockerfile which uses a sha256: hash in FROM

**Output of `hadolint --version` or
  `docker run --rm hadolint/hadolint hadolint --version`:**

```bash
Haskell Dockerfile Linter 1.11.2-no-git
```

**Dockerfile** (if relevant)

```Dockerfile
FROM ruby:2.5@sha256:e1dc5bd27600a5e1ac190565f5573590b3610371bd995e9cc2b445b7d22f3cc4
```

**Additional environment details (OS, stack version, etc.)**

Error message: `Dockerfile:1:21 unexpected ':' expecting a new line followed by the next instruction, at least one space, or the image tag`

**Comment by timbru31** [comment]
Yes, see https://docs.docker.com/engine/reference/commandline/images/#list-image-digests section „List Image digests“

**Comment by gaahrdner** [comment]
>  Why have a tag AND a digest at the same time?

You could push a different image and overwrite a tag, which could be a security issue.  Pinning a `FROM`  command to a sha256sum would alleviate this.

**Comment by lorenzo** [comment]
Pinning to a sha works fine, what I was not aware of and is not documented in the docker page is that you could both have a tag and a sha :)

**Comment by timbru31** [comment]
Works great, thanks!
