### ISSUE TITLE
[Question] Web Interface or API

### ISSUE THREAD

**Issue by superpoussin22** [hadolint/hadolint#264]
- [] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

Did you plan to provide a web interface with or  API to use with Hadolint like you have on your web site ?

Thanks

**Comment by lorenzo** [comment]
It's been on my mind for a while, but haven't had time to do this. Ideally I could figure out how to compile haskell to javascript and use the generated code as a library.

The worst case is to setup a server where the binary is invoked, but I don't have time for that. Would you like to help implementing something along those lines?

**Comment by lorenzo** [comment]
I finally got around to doing this: https://hadolint.github.io/hadolint/f

**Comment by bsecker** [comment]
@lorenzo is the source code for the github.io page available anywhere? Cheers :-)

**Comment by bsecker** [comment]
@lorenzo im interested in hosting a Fully-internal (ie no reliance on external websites) "lint my dockerfile" Web page. The idea would be essentially the github.io page where people can use a self-service portal to check their Dockerfiles without having to install hadolint locally.
