### ISSUE TITLE
Access main functions and data structures and all rules programmatically

### ISSUE THREAD

**Issue by jllopes** [hadolint/hadolint#265]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

I'm trying to make a wrapper for Hadolint and I need access to some functions and data structures from the Main file (Lint and LintOptions). 
I've managed to do it but I had to do a refactor that renamed the current Main.hs so I could import the functions from that file to a different one.

So I was wondering if you guys would have any ideas on how to make the functions from the Main.hs file accessible in different files?

Also, is there a way to access all existing Hadolint rule names and descriptions programmatically to generate some JSONs?

**Comment by lorenzo** [comment]
Just move the functions to a file inside the library (src folder) and call the functions from the Main file. I will merge the PR if you want to work on this.

**Comment by lorenzo** [comment]
There is no way to access the descriptions programmatically at this point, other than doing some functional contorsions :)
