### ISSUE TITLE
Also lint separate shell script files

### ISSUE THREAD

**Issue by mcandre** [hadolint/hadolint#284]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

Hadolint does a good job linting `RUN` directives in Dockerfile's, considering many corner cases and risks of shell code. However, many Dockerfile's move the bulk of their provisioning logic into separate shell script files. Could Hadolint suggest the same improvements for shell code in external scripts, as well as inline in Dockerfiles?

**Comment by lorenzo** [comment]
One thing that I'd like to avoid In general is having to external files other than the passed docker file. Have you tried using shellcheck as a companion to hadolint?

**Comment by mcandre** [comment]
Yes, I do. ShellCheck, bashate, checkbashisms, etc. do not offer the same linting rules as hadolint.

Perhaps hadolint could offer the ability to lint shell script files in addition to shell script inline Dockerfiles?

**Comment by lorenzo** [comment]
Hadolint uses ShellCheck internally, what do you mean it does not use the same rules?

**Comment by mcandre** [comment]
Hmm, maybe I've been using an out of date version of ShellCheck. But I noticed that hadolint (or perhaps it was one of the other Dockerfile linters?) would suggest additional cleanup steps after `apt-get remove`...

**Comment by lorenzo** [comment]
I see what you mean now. Those are rules implemented by hadolint. I'll reopen since it is an interesting idea to provide the extra rules to external scripts somehow

**Comment by lorenzo** [comment]
I believe the best path forward is to add `shellcheck` to your pipeline instead of adding it directly to hadolint
