### ISSUE TITLE
DL3002: Do not switch to root USER not always valid

### ISSUE THREAD

**Issue by aweiteka** [hadolint/hadolint#29]
While I agree with the general principle, I encountered the need to switch to root in a situation where the base docker image was non-root but I needed to install additional software via yum. Here's the Dockerfile: 
https://github.com/redhataccess/ascii_binder/blob/master/Dockerfile

**Comment by lukasmartinelli** [comment]
> While I agree with the general principle, I encountered the need to switch to root in a situation where the base docker image was non-root but I needed to install additional software via yum. Here's the Dockerfile:

Yes I found that in practice as well - it is a bit too aggressive. Will probably remove the rule.

**Comment by aweiteka** [comment]
Maybe it's better as a lower severity level so people take note of it but it doesn't fail.
