### ISSUE TITLE
Intermittent segfault in Ubuntu 16.04 WSL

### ISSUE THREAD

**Issue by 27Bslash6** [hadolint/hadolint#293]
- [x] This is a bug report
- [x] I searched existing issues before opening this one

### Expected behavior
It should work reliably and not segfault in Ubuntu WSL

### Actual behavior
Random segfaults, perhaps 1 in 4 attempts are successful

### Steps to reproduce the behavior
```bash
$ hadolint --version
[1]    17054 segmentation fault (core dumped)  hadolint --version
$ hadolint --version
[1]    17054 segmentation fault (core dumped)  hadolint --version
$ hadolint --version
Haskell Dockerfile Linter v1.16.0-0-g475ad7
```

**Additional environment details (OS, stack version, etc.)**
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
$  uname -a
Linux DESKTOP-4K7V934 4.4.0-17134-Microsoft #523-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
````

I'm not sure how to generate coredumps for inspection, according to https://github.com/Microsoft/WSL/issues/1262 they're not available yet?

**Comment by lorenzo** [comment]
I don’t know much about WSL, are you running the windows binary or the Linux binary?

**Comment by 27Bslash6** [comment]
The linux binary:

```
$ sha256sum $(which hadolint)
104bb5cec00de99a2a041b584877581125bcc2607c0e24fe730a55cbec4043f3  /usr/local/bin/hadolint
```

**Comment by lorenzo** [comment]
Ok, it must be differences with libc causing this as it is dynamically linked. Would you mind trying a previous release of hadolint and report of the issue is still present? 

If it still is, then the only solution would be to produce a truly static binary, but that will require a re-work of our CI.

**Comment by 27Bslash6** [comment]
Sure, I've just tried with 1.15 and 1.14 and they both exhibit the same random segfaults. Would you like me to keep going back?

**Comment by lorenzo** [comment]
No, I think that's enough. I will look into how we can change our CI to be able to produce static binaries.

**Comment by lorenzo** [comment]
In the meantime, you can use the docker release, which is known to work without issues.
