### ISSUE TITLE
Upload to Linux package manager

### ISSUE THREAD

**Issue by PatMyron** [hadolint/hadolint#312]
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior
`apt-get install hadolint`
### Actual behavior
`Unable to locate package hadolint`
### Steps to reproduce the behavior
https://github.com/PatMyron/pocket-lint/runs/90578242

**Comment by zemanlx** [comment]
Sorry we do not support installation via `apt` or `yum` or `another_package_manager_of_another_linux_family`. All supported options are listed in [README.md](https://github.com/hadolint/hadolint#install). 

My point of view is that packages are useful/necessary if there is a need for dependency management, which we do not have (except `libc` which is there already). Updating packages in distributions usually take time which means that a user will get out of date version of package. 

For example _latest_ `shellcheck` on my Ubuntu 18.04 is `0.4.6` which was released on 26 Mar 2017.
Real _latest_ `shellcheck` is `0.6.0` released on 3 Dec 2018.

I prefer to use binaries using `wget` or `curl`, eg. to install our latest version `1.16.3` to `/bin`

```
wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
```

If there is a desperate need for package manager, `brew` is always building real _latest_ of hadolint.

**Comment by PatMyron** [comment]
Ironically, I've come to agree with @zemanlx about distro package managers since opening this issue
However, managing package versions is tricky when simply downloading executables, so I usually prefer language-specific package managers nowadays, but Haskell's obviously not the most mainstream language, so `brew` seems fine
