### ISSUE TITLE
To support the use of remote configuration file [Docker]

### ISSUE THREAD

**Issue by oyewaleoyelami** [hadolint/hadolint#319]
- [ ] This is a bug report
- [x] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior
should be able to use a remote configuration file instead of a local one
### Actual behavior
`` Yaml file not found: remoteUrl/myconfig.yml
CallStack (from HasCallStack):
  error, called at app/Main.hs:108:25 in main:Main
1 ``
### Steps to reproduce the behavior
`docker run --rm -v "$PWD:/test" -w /test hadolint/hadolint hadolint --config remoteUrl/myconfig.yml Dockerfile `

**Output of `hadolint --version` or
  `docker run --rm hadolint/hadolint hadolint --version`:**

` v1.16.3-2-g4b0e6bc`

 I am trying to achieve using a centralized configuration across multiple projects. I would have loved to send a PR instead but not really a Haskell person or someone should point me in the direction if there exists an approach to achieve this already.

**Comment by lorenzo** [comment]
I would rather not make hadolint fetch things from the network. Is it not possible for you to download the file beforehand?

**Comment by oyewaleoyelami** [comment]
It is possible to download it beforehand but the context of usage is to centralize the configuration and we want to make sure all devs (using our delivery pipeline) comply to same preferred rules across all teams.

**Comment by lorenzo** [comment]
Is building your own docker image an alternative to you? In your own image you could download the file beforehand and then invoke the binary from the official image.

**Comment by oyewaleoyelami** [comment]
I will discuss this approach with the rest of the team and revert. Thanks for the suggestion
