### ISSUE TITLE
Basic docker un does not work

### ISSUE THREAD

**Issue by pascalandy** [hadolint/hadolint#321]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

```
docker run --rm hadolint/hadolint hadolint --version
Haskell Dockerfile Linter v1.16.3-4-gc7f877d
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
```

**Dockerfile** (if relevant)

```Dockerfile
(paste content of your Dockerfile)
```

**Additional environment details (OS, stack version, etc.)**

mac 10,13,6

**Comment by SuperSandro2000** [comment]
Forks on Ubuntu 19.04. Seems to be a Mac specific issue.

**Comment by pascalandy** [comment]
Something was off with brew. Fixed it on my machine :)
