### ISSUE TITLE
Online linter doesn't work

### ISSUE THREAD

**Issue by Rotzbua** [hadolint/hadolint#331]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior

Working online lint:
http://hadolint.lukasmartinelli.ch/

### Actual behavior

Timeout on API:
http://api.hadolint.lukasmartinelli.ch/

### Steps to reproduce the behavior

go to website -> click `lint` -> no reaction

**Comment by lorenzo** [comment]
We don't currently provide an online linter. It's something that I would like to offer, but have not real time to implement.
