### ISSUE TITLE
Customizable Severity of Rules

### ISSUE THREAD

**Issue by chess-levin** [hadolint/hadolint#340]
- [] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior
There should be a way to customize the behavior if a rule validation breaks. There should be rules when they break hadolint returns an error code on exit and other rules should only show a warning and return 0.
In our case we have some rules that must be followed and other rules we only like to warn the user to optimized their Dockerfile.
This leads to Severity Levels like: Major, Minor and a kind of quality gate, where you define when your validation breaks.
This is the same behavior known from SonarQube. 
BTW: It would be great to have a SonarQube Plugin for hadolint results.

### Actual behavior
On any breaking rule hadolint exits with an error code != 0

**Comment by lorenzo** [comment]
For the time being, you can ignore rules that are not critical to your system, or format the rules using JSON or checkstyle and write your own logic.

If you would like to contribute a SonarQube plugin or the customisation feature, let me know and I can guide you in the process of creating a pull request for this repo.

**Comment by chess-levin** [comment]
Could you explain 

> or format the rules using JSON or checkstyle and write your own logic

a little further?

**Comment by lorenzo** [comment]
This was recently implemented
