### ISSUE TITLE
Document: Export report in a commonly used parsable format

### ISSUE THREAD

**Issue by tomasbjerre** [hadolint/hadolint#348]
- [ ] This is a bug report
- [x] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior

I got a request on supporting this tool: https://github.com/tomasbjerre/violations-lib/issues/77

I found this code:
https://github.com/hadolint/hadolint/blob/master/src/Hadolint/Lint.hs#L29

Looks like it is supported? But I cannot find docs on how to use it.

**Comment by lorenzo** [comment]
It is documented in the cli help output, call

   hadolint -h

And you should see more info

**Comment by tomasbjerre** [comment]
Ok, I would still recomend documenting it in the readme. So that people who are googling for a solution don't have to download the tools and run it to see the documentation.

But it is totally up to you, this tool looks great!

**Comment by lorenzo** [comment]
@tomasbjerre help would be most appreciated. If you have a couple of minutes to contribute your findings, you will ensure my gratefulness 😄
