### ISSUE TITLE
Write access to wiki

### ISSUE THREAD

**Issue by vidavidorra** [hadolint/hadolint#358]
- [ ] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

Just wanted to check you guys know everyone can edit the Wiki, not just collaborators. I've just updated the rationale URL of [DL3008](https://github.com/hadolint/hadolint/wiki/DL3008) and noted that no write permission or anything was needed.
If you guys are aware this can be closed right away!

**Comment by lorenzo** [comment]
I'm aware of it... so far no one has abused it and only received good contributions. Thanks for your concern!
