### ISSUE TITLE
hadolint 1.17.4 homebrew upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [hadolint/hadolint#380]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

We have issue upgrading hadolint to either v1.17.4 or v1.17.3 (same error log for both)
Relates to 
- v1.17.4 upgrade, https://github.com/Homebrew/homebrew-core/pull/48554/ 
- v1.17.3 upgrade, https://github.com/Homebrew/homebrew-core/pull/47018

Build log, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/54565/version=mojave/console

**Additional environment details (OS, stack version, etc.)**

Failed on Catalina, Mojave, and HighSierra.

**Comment by lorenzo** [comment]
Hi, I'm not sure why you use cabal for installing hadolint when the installation method we use is stack.

Can you guys use any of the pre-compiled binaries?

**Comment by zemanlx** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/commit/5d1c954ed73ac201021deb45ba8841852044d943
