### ISSUE TITLE
Export/output AST

### ISSUE THREAD

**Issue by dAnjou** [hadolint/hadolint#383]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

Hi, is it possible to export/dump the AST somehow, so that I can work with it in another program (that I'm planning to write)?

**Comment by lorenzo** [comment]
You can use the [library we use](https://github.com/hadolint/language-docker), and print the resulting AST to stdout.

These lines would accomplish the goal: https://github.com/hadolint/language-docker/blob/master/examples/parse.hs

**Comment by dAnjou** [comment]
Unfortunately I have no experience with Haskell, I'm using another language, so I can't use that library 🙁

**Comment by lorenzo** [comment]
@dAnjou, fortunately, you don't need experience. If you just copy the code I linked, it will print the AST representation in stdout. Let me know if you need further guidance.
