### ISSUE TITLE
Find usage of relative COPY without WORKDIR

### ISSUE THREAD

**Issue by SuperSandro2000** [hadolint/hadolint#390]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

Today I fixed a bug caused by removing a WORKDIR instruction and not updating the paths of several COPY ones.

Now my suggestion would be to lint if a COPY destination is relative and no WORKDIR was set previously and let the user know that he should either set a WORKDIR or set a absolute path.

**Comment by lorenzo** [comment]
This is a great idea!

Is this something you would like to help implement yourself? I can offer some guidance

**Comment by SuperSandro2000** [comment]
I have no prior experience with Haskell or any purely functional programming language so I would like if someone else could do it. :)
