### ISSUE TITLE
Suppress Exit Code

### ISSUE THREAD

**Issue by CCFenner** [hadolint/hadolint#391]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior

When running in a CICD environment, I would like to suppress the exit code on findings. That way I would know when the command fails due to wrong usage (file missing) and could evaluate the results that are written to a checkstyle result file later on in Jenkins / SonarQube. 
I would like to pass something like `--suppress-exit-code`

### Actual behavior

Exit code is `1` if I have finding and command execution issues.

**Comment by CCFenner** [comment]
Looks like this is already in place for `codacy` and `codeclimate`.

https://github.com/hadolint/hadolint/blob/23c3bda375ac76e1e81c1ff16361c53d8d252811/src/Hadolint/Lint.hs#L49-L50

**Comment by saxonww** [comment]
Just to add to this: I want to get the exit code even when saving a codeclimate report, but found that hadolint suppresses the exit code.

It would be wonderful if hadolint had a consistent default across all reporting modes, and let the user select whether to suppress the exit code or not. Adding support for setting this via the config file would be great.
