### ISSUE TITLE
Suggest ``yarn cache clean`` when ``yarn [install]`` was run

### ISSUE THREAD

**Issue by SuperSandro2000** [hadolint/hadolint#395]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Suggestion

Yarn can generate quite large caches that can easily be 100MB or 300MB big.
I think hadolint should tell you to use ``yarn cache clean`` in the same layer you installed something to avoid keeping those caches in the final image.

**Comment by ghostsquad** [comment]
Or use a multiple stages, which is likely better anyway, since you may need to install dev dependencies, then uninstall those before finalizing the final image.
