### ISSUE TITLE
online linter doesn't seem to work

### ISSUE THREAD

**Issue by kidbrax** [hadolint/hadolint#410]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior
when pressing 'Lint' at https://hadolint.github.io/hadolint/ it doesn't seem to do anything. No success or failure feedback.

### Actual behavior
Nothing

### Steps to reproduce the behavior
go to https://hadolint.github.io/hadolint/ and press Lint

**Comment by lorenzo** [comment]
If no errors, the editor won't show any feedback. Try making a mistake

**Comment by kidbrax** [comment]
Ok, it does work when making a mistake. Thanks. However, I would suggest adding some feedback when it is correct. Otherwise, it looks like it is doing nothing.

**Comment by lorenzo** [comment]
I think this is "fixed" as there is a load spinner in the button now
