### ISSUE TITLE
CROSS_BUILD_COPY

### ISSUE THREAD

**Issue by huornlmj** [hadolint/hadolint#424]
- [ ] This is a bug report
- [ ] This is a feature request
- [X ] I searched existing issues before opening this one

Some Dockerfiles I have from Kubernetes test images contain the following construct: 

`FROM BASEIMAGE

CROSS_BUILD_COPY qemu-QEMUARCH-static /usr/bin/`

But hadolint reports:  

unexpected 'C' expecting '#', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, end of input, or whitespace

**Comment by zemanlx** [comment]
Hmm, that does not look like valid Dockerfile. Can you share whole file?

**Comment by huornlmj** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/images/cuda-vector-add/Dockerfile

**Comment by lorenzo** [comment]
that's definitely not a valid dockerfile

**Comment by lorenzo** [comment]
Closing as there hadolint is reporting the error correctly
