### ISSUE TITLE
"unexpected '%' expecting a new line followed by the next instruction or at least one spacew"

### ISSUE THREAD

**Issue by WyriHaximus** [hadolint/hadolint#428]
- [x] This is a bug report
- [ ] This is a feature request
- [X] I searched existing issues before opening this one

### Expected behavior

Lint the docker file

### Actual behavior

Crashed with the following error:
```
^@^@/project/Dockerfile-fpm:12:41 unexpected '%' expecting a new line followed by the next instruction or at least one space 
```

### Steps to reproduce the behavior

```
docker run -v ${current_dir}:/project:ro --workdir=/project --rm -it hadolint/hadolint:latest-debian hadolint /project/Dockerfile-cli /project/Dockerfile-fpm /project/Dockerfile-http
```

**Output of `hadolint --version` or
  `docker run --rm hadolint/hadolint hadolint --version`:**

We're using `hadolint/hadolint:latest-debian` to run hadolint, 
Digest: sha256:5e040965e5aa0b0246bf739432a7df2f0755e38897de03ee211eb80ad3f32554

```bash
^@^@/project/Dockerfile-fpm:12:41 unexpected '%' expecting a new line followed by the next instruction or at least one space 
```

**Dockerfile** (if relevant)

```Dockerfile
# syntax=docker/dockerfile:experimental
FROM php:7.2-fpm-alpine3.7 as fpm
ENV PHP_FPM_ACCESS_FORMAT="%R - %u %t \"%m %r\" %s"
```

Runs in CircleCI.

Best part is that it builds and runs fine, seems that hadolint chokes on the `%` for some reason

**Comment by lorenzo** [comment]
I'm in the process of rewriting the parser, I'll add this to the test suite and see if it was already fixed. Thanks for reporting!

**Comment by WyriHaximus** [comment]
Ah awesome, missed your message and already filed a PR for this just adding the tests for now: https://github.com/hadolint/language-docker/pull/53

**Comment by WyriHaximus** [comment]
🎉 thanks!
