### ISSUE TITLE
Add a new rule to detect supported architectures of a dockerfile

### ISSUE THREAD

**Issue by odidev** [hadolint/hadolint#429]
Hi Team,

I am interested in adding a support in hadolint tool for detecting if the dockerfile is architecture-specific.
ex : If my base image in the FROM clause is aarch64 architecture-specific, and I am linting that dockerfile on x86_64 platform, then a rule should pop up saying that “the base image is not supported on this architecture”.

We can use the "docker manifest inspect" experimental command to fetch architecture information from the image's manifest.

I have tested the same in the "main" module defined in Main.hs file, and am able to get the required result there.

I suggest that maybe we can add a new rule, by adding a similar configuration in Rules.hs to detect the supported architectures of a dockerfile.

Please share your opinion on the same.

**Comment by lorenzo** [comment]
Currently hadolint is limited to doing checks that only depend on the contexts of the dockerfile and not the environment.

There seems to be an increasing need for checks of that type, but this would require architecting hadolint in a different way. 

Maybe we can gather requirements first for those types of checks first before embarking on such architecture. For instance, how would we enable these checks, whether or not they are run before the others, if other checking should continue, what other environment depender checks we can make, etc.

**Comment by rhenwood-arm** [comment]
@lorenzo - thanks for this. I've been working with @odidev on this. A specific suggestion for a rule I would like to explore is:

## Do not use --platform= with FROM.

### Problematic code:

```dockerfile
FROM --platform=x86 busybox
```

### Correct code:

```dockerfile
FROM busybox
```

### Rationale:

Specifying `--platform=` in the [docker file FROM clause](https://docs.docker.com/engine/reference/builder/#from) forces the Image build to only target one platform. This has a number of negative consequences:
- It is not possible to build a [multi-platform Image](https://www.docker.com/blog/docker-official-images-now-multi-platform/) from this Docker file.
- The platform that you build on must be the same as the platform specified in `--platform=`

A better approach is omit `FROM --platform` in the docker file and to specify `buildx --platform=` during the build if control of the image platform target is needed.

**Comment by SuperSandro2000** [comment]
If you run ``docker run --rm --privileged multiarch/qemu-user-static --reset -p yes`` before building the image it is still possible but we should probably disencourage people to use that feature for above reasons. People who know what they are doing can ignore this.

**Comment by lorenzo** [comment]
I think we could implement that rule without using the environment, no? If we always suggest not to use platform but build flags, that’s an entirely static check.

**Comment by SuperSandro2000** [comment]
@lorenzo that is what I thought. In the end we supply suggestions and you are not enforced to follow them.

**Comment by odidev** [comment]
@lorenzo and @SuperSandro2000 ,

Thanks for the reply.

Can you please add a new rule to detect usage of “--platform=” in the ‘FROM’ clause of dockerfile or please let me know if any help is required.
