### ISSUE TITLE
Usage of the cat container logo in context of hadolint findings

### ISSUE THREAD

**Issue by amandel** [hadolint/hadolint#449]
- [x] This is a Question 

I've just filed a pull request to support the hadolint native json format with the warnings-ng Jenkins plugin. The plugin then displays the findings of hadolint together with other static code analysis tools and also collects differences in findings over time etc.
   
Now to my Question: Is it permitted to use the cat container logo as icon for hadolint findings.

My PR: https://github.com/jenkinsci/warnings-ng-plugin/pull/551 (includes already the logo (hide))

**Comment by zemanlx** [comment]
Hi @amandel,

I do not see any issue with using Hadolint icon if you make sure that you refer to our Hadolint.

**Comment by amandel** [comment]
Great, thank you.
