### ISSUE TITLE
Deploy the container image to ghcr.io

### ISSUE THREAD

**Issue by angelbarrera92** [hadolint/hadolint#503]
- [ ] This is a bug report
- [X] This is a feature request
- [X] I searched existing issues before opening this one

### Expected behavior

I want to pull the official container image from the GitHub container registry instead of from DockerHub.

### Actual behavior

Due to the latest DockerHub rate limits, we have some problems while pulling this software from DockerHub. 

### Steps to reproduce the behavior

docker pull like there is no tomorrow :)

I can work on it if you think it is a good idea!

**Comment by lorenzo** [comment]
Sounds like a great idea, can you help us by sending a pull request with the changes?

**Comment by angelbarrera92** [comment]
> Sounds like a great idea, can you help us by sending a pull request with the changes?

Yes! But first I have to understand how you publish them :)

I see you are not using GitHub action to build the containers. So... How do you do it?
I can see a couple of scripts under the docker/hooks directory:

https://github.com/hadolint/hadolint/blob/master/docker/hooks/build
https://github.com/hadolint/hadolint/blob/master/docker/hooks/push

What system triggers these scripts? Are you using the DockerHub build system?
Do you want to maintain both? (DockerHub and ghcr.io)

Thanks!

**Comment by lorenzo** [comment]
We are using the dockerhub build system. For the time being, leave dockerhub alone and add a github action workflow to publish there too

**Comment by angelbarrera92** [comment]
> We are using the dockerhub build system. For the time being, leave dockerhub alone and add a github action workflow to publish there too

Makes sense, i'll do :)

**Comment by angelbarrera92** [comment]
@lorenzo ready to be reviewed: https://github.com/hadolint/hadolint/pull/504
