### ISSUE TITLE
Badge Hadolint

### ISSUE THREAD

**Issue by mBouamama** [hadolint/hadolint#505]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior
A badge from shields.io which attested hadolint test passed
### Actual behavior
- expected:  badge from shields.io like this [![mBouamama](https://circleci.com/gh/mBouamama/MyJWT.svg?style=shield)](https://circleci.com/gh/mBouamama/MyJWT.svg?style=shield)

**Comment by l0b0** [comment]
I just created https://img.shields.io/badge/hadolint-passing-brightgreen for use in a project.

**Comment by mBouamama** [comment]
Thanks you @l0b0 , its perfect! Great work

**Comment by l0b0** [comment]
By the way, you can trivially create arbitrary badges simply by modifying that URL: the last part of the path is basically just a URL-encoded prefix, suffix and colour.
