### ISSUE TITLE
Binary hadolint github download crashes on macOS Big Sur

### ISSUE THREAD

**Issue by mathbunnyru** [hadolint/hadolint#508]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior

```
wget https://github.com/hadolint/hadolint/releases/download/v1.19.0/hadolint-Darwin-x86_64
chmod+x hadolint-Darwin-x86_64
./hadolint-Darwin-x86_64 --help
some help output
```

### Actual behavior

```
fish: './hadolint-Darwin-x86_64 --help' terminated by signal SIGKILL (Forced quit)
```

**Additional environment details (OS, stack version, etc.)**

I use latest macOS Big Sur 11.0.1 Intel chip (not M1).

Homebrew version works fine.

**Comment by lorenzo** [comment]
seems fixed with latest release
