### ISSUE TITLE
About release `1.20.0`

### ISSUE THREAD

**Issue by chenrui333** [hadolint/hadolint#524]
👋  just a friendly reminder that it looks like the most release tag `1.20.0` was not marked as latest release, not sure if that is intentional. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/69855

**Comment by lorenzo** [comment]
Oh, sorry. It was an oversight

**Comment by chenrui333** [comment]
that makes sense, thanks @lorenzo!
