### ISSUE TITLE
[BUG] Hadolint ≥ v1.20.0 depends on glibc; broken in Alpine Linux

### ISSUE THREAD

**Issue by skyzyx** [hadolint/hadolint#534]
- [x] This is a bug report

### Expected behavior

Hadolint should work on Alpine Linux, like it did in v1.19.0, as a self-contained binary.

### Actual behavior

Hadolint appears to rely on outside C dependencies like `libgmp` and `glibc` — the latter of which is not packaged for Alpine Linux.

### Steps to reproduce the behavior

```bash
[root@cef36932cd79: ~ ] $ find / -name hadolint
/usr/local/bin/hadolint

[root@cef36932cd79: ~ ] $ apk add gmp
OK: 238 MiB in 118 packages

[root@cef36932cd79: ~ ] $ /usr/local/bin/hadolint
Error relocating /usr/local/bin/hadolint: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __fprintf_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __sprintf_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __memcpy_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __printf_chk: symbol not found

[root@cef36932cd79: ~ ] $ apk add musl-utils
OK: 238 MiB in 118 packages

[root@cef36932cd79: ~ ] $ ldd /usr/local/bin/hadolint
/lib/ld-musl-x86_64.so.1: /usr/local/bin/hadolint: Not a valid dynamic program
```

**Output of `hadolint --version` or
  `docker run --rm hadolint/hadolint hadolint --version` or
  `docker run --rm ghcr.io/hadolint/hadolint hadolint --version`:**

```bash
[root@cef36932cd79: ~ ] $ hadolint --version
Error relocating /usr/local/bin/hadolint: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __fprintf_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __sprintf_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __memcpy_chk: symbol not found
Error relocating /usr/local/bin/hadolint: __printf_chk: symbol not found
```

**Dockerfile** (if relevant)

```Dockerfile
ENV HADOLINT_VERSION 1.21.0

# Install hadolint
RUN curl -sSLf -o hadolint https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64
RUN chmod +x hadolint
RUN mv hadolint /usr/local/bin
RUN hadolint --version
```

**Additional environment details (OS, stack version, etc.)**

* Alpine Linux 3.13.latest (musl, not glibc)
* x86_64
* Also appears to depend on `libgmp.so`.

I don't know the first thing about Haskell, but I'm looking at the [diff between releases](https://github.com/hadolint/hadolint/compare/v1.19.0...v1.21.0), and an educated guess says it has something to do with this new file: [hadolint.cabal](https://github.com/hadolint/hadolint/blob/cb19447de571d0c88b1650dd3e2e42d0c637f445/hadolint.cabal)

**Comment by skyzyx** [comment]
Also tested against v1.20.0, which also has these breaking dependencies.

**Comment by lorenzo** [comment]
hmm, probably the new build script broke the static linker configuration. I'll try to bring that back
