### ISSUE TITLE
DL3020 Use ADD to add URL resources (fetch from network instead of local copy)

### ISSUE THREAD

**Issue by ye** [hadolint/hadolint#55]
While majority of the cases `COPY` is preferred over `ADD` in Docker's best practices guide, there are two exceptions [1]:
1. tarball file (either local or remote) extraction into image during build
2. resources fetched from the network

Currently, DL3020 rule doesn't account for the case 2 where <src> is an URLs, which should not be a violation of the best practices. See below for a legitimate use case:

``` bash
$ cat <<EOF | hadolint --ignore DL3007 -
> FROM busybox:latest
> MAINTAINER Ye Wang <ye@users.noreply.github.com>
> 
> ADD "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64" /bin/jq
> RUN chmod +x /bin/jq
> ENTRYPOINT ["jq"]
> EOF
/dev/stdin:4 DL3020 Use COPY instead of ADD for files and folders
```

**Note:** although they said "fetching packages from remote URLs is strongly discouraged" [2] in the best practices guide, I think that is debatable as the argument is against remote URLs to tarball archives that leads to inefficient file extractions. So that's really first case above.

[1] https://docs.docker.com/engine/reference/builder/#add 
[2] https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/add-or-copy

**Comment by JonathanDoughty** [comment]
And I'd add that ADDing a file that ends in an archive extension, especially a compressed archive, suggests the user wants that archive expanded - since it will be anyway - and thus is depending on case 1 where ADD is preferred to COPY followed by a `RUN tar xjf xxx`or something; where you would end up making the image larger than it needs to be.

**Comment by Frodox** [comment]
COPY is preferred way to use in Dockerfile according to practice, real experience and best-practice ( https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy ). It is more obvious what happens

**Comment by rlees85** [comment]
`COPY` cannot add a URL. As long as Docker supports `ADD`ing directly from a URL I don't see why it would be a linting failure.

**Comment by eddybl** [comment]
> COPY is preferred way to use in Dockerfile according to practice, real experience and best-practice ( https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy ). It is more obvious what happens

Except for a tar ball OR a remote url, which is excatly what OP is mentioning?

**Comment by Frodox** [comment]
> Except for a tar ball OR a remote url

Well, just do not use `ADD` at all, and you would reduce potential problems :man_shrugging: 
Press 'C' for Consistency  :D
