### ISSUE TITLE
Is Docker required to install Hadolint?

### ISSUE THREAD

**Issue by pzelnip** [hadolint/hadolint#558]
- [ ] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior

Not an issue, a question: is Docker required to be installed to use Hadolint?  This machine is an M1-powered Macbook, and I don't want to install the preview version of Docker if I don't have to, but I do have to write Dockerfiles while on this machine (my intention is to build said images via my CI pipeline).

**Comment by lorenzo** [comment]
No, you can also download the binaries from the releases page in github. I have not tested the binaries in an M1 (I hope they would work with rosetta)

**Comment by pzelnip** [comment]
Perfect thanks.

And I can confirm that the x86 binaries work under M1 with Rosetta.  Just grabbed the 1.23.0 binary and threw it in my path, and works fine.

Thanks!

**Comment by kamalteja** [comment]
**For future investigators:**
I tried our docker version 1.23.0 and get bss_size overflow issue with rosetta. Current latest version 2.12.0 works fine. Didn't check at what version the breaking change was introduced.
