### ISSUE TITLE
v2.1.0 tags are missing on dockerhub

### ISSUE THREAD

**Issue by Stikus** [hadolint/hadolint#590]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior
![image](https://user-images.githubusercontent.com/41360525/113398255-f6d5e800-93a6-11eb-8ab9-fc2c0704b7e3.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/41360525/113398231-e7ef3580-93a6-11eb-998f-db829f3ec309.png)

### Steps to reproduce the behavior
Check [dockerhub](https://hub.docker.com/r/hadolint/hadolint/tags?page=1&ordering=last_updated)

`vVERSION` tags are no longer supported or this is overlook?

**Comment by lorenzo** [comment]
Pushed the tags. Need to fix the release script to keep the old versioning scheme
