### ISSUE TITLE
Improve .hadolint.yaml documentation

### ISSUE THREAD

**Issue by Mazorius** [hadolint/hadolint#602]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

# Background

As seen in #600 the error message is not up to date.

Maybe you should update the [Hadolint JSON schema] as requested in #601 (https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/hadolint.json) and mention this in the error instead of printing examples?

Or a detailed configuration file description under documentation could be established which will link to the JSON schema.

What do you think about this?

**Comment by lorenzo** [comment]
Sounds like a good idea. I'm all for improving the documentation. I like printing examples as help, though.

Would you like to take on this task?

**Comment by Mazorius** [comment]
I will try 😄

**Comment by lorenzo** [comment]
thanks!!

**Comment by Mazorius** [comment]
@lorenzo do you want to stay with markdown or is AsciiDoc also possible?

**Comment by lorenzo** [comment]
@markus1189 markdown.

**Comment by m-ildefons** [comment]
I'm looking into updating the schema for schema store. There is the option to [self-host](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#self-hosting-schemas) such a schema as part of this repository. Or I can just submit a PR there. Which is preferred?

**Comment by Mazorius** [comment]
I think the best way is, to create a self-hosted and register always the latest release version in the catalog during a release?
Like for example angular is doing it.
What do you think @lorenzo ?

**Comment by lorenzo** [comment]
yeah, that makes sense to me. Let me know if you need help doing that @Mazorius
