### ISSUE TITLE
Putting hadolint on conda-forge

### ISSUE THREAD

**Issue by janjagusch** [hadolint/hadolint#608]
I'm trying to put hadolint on [conda-forge](https://github.com/conda-forge) so you can install it with [conda](https://github.com/conda/conda).

I don't know much about Haskell or packaging Haskell software, so it would be cool if one of the maintainers could take a look at my [pull request to add hadolint to conda-forge](https://github.com/conda-forge/staged-recipes/pull/14581/files). 

I'd would also be cool if one of the maintainers would volunteer to join me as a recipe maintainer. Usually the work required is super minimal (at most bumping a version number). But if the recommended way to build Hadolint from source changes, it would be nice to have a maintainer on board.

Thanks a lot for your help. :)

**Comment by lorenzo** [comment]
could you download the prebuilt binary from GitHub instead?

**Comment by janjagusch** [comment]
> could you download the prebuilt binary from GitHub instead?

Yes, that's what I'm doing for Linux and Windows. For OSX, I'm building from source, though. Now that I'm checking the release section again, I could probably just use the `-Darwin` binary for OSX, right?

**Comment by janjagusch** [comment]
> > could you download the prebuilt binary from GitHub instead?
> 
> Yes, that's what I'm doing for Linux and Windows. For OSX, I'm building from source, though. Now that I'm checking the release section again, I could probably just use the `-Darwin` binary for OSX, right?

I'm now using the `-Darwin` prebuilt binary for the OSX build. Everything seems to work. Thanks, @lorenzo!

**Comment by maresb** [comment]
This effort continues in https://github.com/conda-forge/staged-recipes/pull/14581
