### ISSUE TITLE
Log which config file was used

### ISSUE THREAD

**Issue by rittneje** [hadolint/hadolint#610]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

It would be helpful if hadolint output a log message indicating which config file it was using. Right now it doesn't say anything, so you can't easily tell. For example, if you accidentally name the file `hadolint.yaml` instead of `.hadolint.yaml`, you won't know unless you explicitly test a negative case.

**Comment by lorenzo** [comment]
Sounds like a good idea, would you like to contribute this feature? @rittneje

**Comment by rittneje** [comment]
Unfortunately, my experience with Haskell is rather limited.

**Comment by seaerchin** [comment]
hi @lorenzo, i'm currently learning haskell and this seems like a good first issue for me to contribute to. would it be possible for me to pick up this issue?

**Comment by lorenzo** [comment]
@seaerchin sure thing, thanks for stepping up!

Let me know if you need any guidance.

**Comment by seaerchin** [comment]
will do! reading through the codebase now and should i just post here if i have questions or should i use another medium?

**Comment by seaerchin** [comment]
i've the PR out [here](https://github.com/hadolint/hadolint/pull/615); still new to haskell (and even newer to the codebase) so lmk if there are stuff that should be done differently
