### ISSUE TITLE
Recognize .hadolint.yml along with .hadolint.yaml as configuration file

### ISSUE THREAD

**Issue by mloskot** [hadolint/hadolint#614]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior

Recognize `.hadolint.yml`

### Actual behavior

Recognizes only `.hadolint.yaml` as per

https://github.com/hadolint/hadolint/blob/74f675eabf910fde339e01613c117c7b7065613b/src/Hadolint/Config.hs#L88-L90

------

It seems like a simple change, but I wish I was familiar with Haskell to offer a PR.

**Comment by seaerchin** [comment]
@lorenzo - i'd like to take a crack at this too! also, is `hadolint` planning to support alternative file formats for configuration in the future or would it be limited to `yaml` exclusively?
