### ISSUE TITLE
Missing DockerHub images for v2.6.1

### ISSUE THREAD

**Issue by rittneje** [hadolint/hadolint#687]
https://hub.docker.com/r/hadolint/hadolint/tags

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I believe these were cancelled (looks like it).

https://github.com/hadolint/hadolint/runs/3238877631
![image](https://user-images.githubusercontent.com/61180606/129272645-cddc57f6-834a-443f-abd1-c2273dbb6843.png)

**Comment by rittneje** [comment]
@lorenzo Given that v2.7.0 was already released and pushed to DockerHub, are you planning to retroactively push v2.6.1, or should I close this?

**Comment by lorenzo** [comment]
I did not manage to retroactively push... I have tried to improve the release process to avoid this issue in the future
