### ISSUE TITLE
GitHub tag out of sync with DockerHub image in pre-commit config

### ISSUE THREAD

**Issue by christianbundy** [hadolint/hadolint#706]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior

pre-commit config in `v2.7.0` tag should reference `v2.7.0` on DockerHub

### Actual behavior

pre-commit config in `v2.7.0` tag references `v2.6.1` on DockerHub

When you release 2.7.1 would you be able to bump the version in the pre-commit config as well please?

https://github.com/hadolint/hadolint/blob/v2.7.0/.pre-commit-hooks.yaml

### Steps to reproduce the behavior

N/A

**Additional environment details (OS, stack version, etc.)**

**Comment by lorenzo** [comment]
Would you like to submit a fix? Bonus points if you can automate it :D

**Comment by christianbundy** [comment]
It's fixed in the default branch (https://github.com/hadolint/hadolint/pull/698), but it looks to me like your version bump commit (https://github.com/hadolint/hadolint/commit/3e13ec6fa67a42fc3be93b85caf2d1451fd1f983) is a manual process.

**Comment by lorenzo** [comment]
it is a manual process, I would appreciate any help in making it fully automated

**Comment by lorenzo** [comment]
we use `latest` in the hook now
