### ISSUE TITLE
v2.7.0 GH release missing a Windows exe + version in Scoop is out of date

### ISSUE THREAD

**Issue by darkvertex** [hadolint/hadolint#728]
- [x] This is a bug report
- [x] I searched existing issues before opening this one

### Expected behavior

`scoop install hadolint` should install the latest version which is 2.7.0 as I write this.

### Actual behavior

`scoop install hadolint` installed 2.6.1 -- probably because this file is out of date:
https://github.com/ScoopInstaller/Main/blob/master/bucket/hadolint.json

### Steps to reproduce the behavior

1. `scoop install hadolint`
2. `hadolint --version`

**Comment by worstpractice** [comment]
Any developments on this?

**Comment by lorenzo** [comment]
just published 2.8.0 with all binaries
