### ISSUE TITLE
The `trustedRegistries` config option does not work / has incorrect documentation

### ISSUE THREAD

**Issue by radomirbosak** [hadolint/hadolint#733]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

![image](https://user-images.githubusercontent.com/4988740/141257833-1cec3d09-e8b5-4ca9-af24-46bc65b7d195.png)

The [documentation](https://github.com/hadolint/hadolint#configure) mentions using the `trustedRegistries` key in config to warn user about untrusted registries, however this key does not work. Instead `trusted-registries` seems to work.

This issue was not present in version 2.7.0 and the config key name change wasn't mentioned in the [release notes](https://github.com/hadolint/hadolint/releases/tag/v2.8.0).

### Expected behavior

```
$ ./hadolint -c config.yml Dockerfile
Dockerfile:1 DL3026 error: Use only an allowed registry in the FROM image
```

### Actual behavior
```
$ ./hadolint -c config.yml Dockerfile
[no output]
```

### Steps to reproduce the behavior

1. Prepare `config.yml`:
```
trustedRegistries:
  - trusted.example.com
```
2 Prepare `Dockerfile`:
```Dockerfile
FROM untrusted.example.com/example:1.0
```

3. Run hadolint:
```shell
$ ./hadolint -c config.yml Dockerfile
```

### Version
2.8.0

It's the linux binary downloaded from [2.8.0 release](https://github.com/hadolint/hadolint/releases/tag/v2.8.0)
```
./hadolint --version
Haskell Dockerfile Linter UNKNOWN
```
(version not showing might be a bug as well)

Additional info:
* OS: Ubuntu 21.04

**Comment by m-ildefons** [comment]
Hi @radomirbosak ,
thanks for the detailed bug report. Yes indeed, the configuration key was renamed in PR  #721 and I mistakenly omitted that in the patch notes.
@lorenzo , should this be reverted to `trustedRegistries` or should it be kept for consistency with the other config options and just updated in the documentation?

**Comment by lorenzo** [comment]
@m-ildefons I did not notice it was renamed. What's the new name? I think it should be reverted as we did not announce that change

**Comment by radomirbosak** [comment]
`trustedRegistries` is what worked before, now `trusted-registries` works instead.
