### ISSUE TITLE
http://hadolint.lukasmartinelli.ch/ not working 

### ISSUE THREAD

**Issue by dhoer** [hadolint/hadolint#75]
Clicking on Lint button doesn't seem to do anything.  

macOS v10.12.2
Chrome v55.0.2883.95 (64-bit)

**Comment by hyperknot** [comment]
I can confirm this.

```
editor.js:17 Uncaught TypeError: Cannot read property 'message' of undefined
    at String.<anonymous> (editor.js:17)
    at Function.each (jquery.js:382)
    at editor.js:16
    at cM (codemirror.min.js:1)
    at H.operation (codemirror.min.js:1)
    at updateHints (editor.js:10)
    at Object.success (editor.js:42)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at x (jquery.js:8264)
(anonymous)	@	editor.js:17
each	@	jquery.js:382
(anonymous)	@	editor.js:16
cM	@	codemirror.min.js:1
operation	@	codemirror.min.js:1
updateHints	@	editor.js:10
(anonymous)	@	editor.js:42
j	@	jquery.js:3099
fireWith	@	jquery.js:3211
x	@	jquery.js:8264
(anonymous)	@	jquery.js:8605
```

**Comment by jgonera** [comment]
Oops, sorry. I skimmed through issues too hastily.

**Comment by roadSurfer** [comment]
Currently failing with CORS:
```Access to XMLHttpRequest at 'http://api.hadolint.lukasmartinelli.ch/dockerfile' from origin 'http://hadolint.lukasmartinelli.ch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

**Comment by lorenzo** [comment]
yes, the service has been shutdown. I don't currently have the means to host it back so it is dead for the time being.

**Comment by lorenzo** [comment]
Moved to https://hadolint.github.io/hadolint/
