### ISSUE TITLE
[Feature] Check image size

### ISSUE THREAD

**Issue by ferquinz** [hadolint/hadolint#779]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Feature request

Reading [this](https://docs.docker.com/develop/dev-best-practices/) about docker image size.
I think it could be interesting to check the base image size to see if its too big or not with a config variable like HADOLINT_IMAGE_SIZE for example.

### Steps to get the size

- Retrieve the base image (Should be different in a multi-arch image
- To check the image size could be done like this:

  `docker manifest inspect -v <registry-domain>/<image-name> | grep size | awk -F ':' '{sum+=$NF} END {print sum}' | numfmt --to=iec-i`

**Comment by ferquinz** [comment]
Also for this purpose could be interesting to check if the project have a .dockerignore file to avoid increasing the image size with unuseful files

**Comment by lorenzo** [comment]
Currently hadolint only deals with the docker file and strives to make no network or system calls. It's a good idea, but it seems would not fit nicely with what hadolint is currently.
