### ISSUE TITLE
Release v2.9.0 missing, though there is a tag v2.9.0

### ISSUE THREAD

**Issue by mathbunnyru** [hadolint/hadolint#792]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

There is a tag v2.9.0, which makes some automatic tools think that there should be a release.
But, there is no release yet and there is no new Docker image available.
Please, make a release when you can.

An example:
https://github.com/jupyter/docker-stacks/pull/1652

**Comment by lorenzo** [comment]
Currently dealing with the broken docker build. I cannot finish the release if there are no docker images produced

**Comment by pkoch** [comment]
I'm assuming this is the failing build? https://github.com/hadolint/hadolint/runs/5544198410?check_suite_focus=true

Is there any assistance a non-Haskeller can provide? Is there a place we can recruit somebody to help, perhaps?

**Comment by pkoch** [comment]
Going for a dumb Google, unsure if it's any help at all.

According to https://www.reddit.com/r/SolusProject/comments/9u6uzt/trouble_installing_intero_using_haskell_stack/, I would expect some `libtinfo` in https://github.com/hadolint/hadolint/blob/master/docker/Dockerfile.

Giving it a try.

**Comment by pkoch** [comment]
It worked! 🎉 Making a PR.
