### ISSUE TITLE
Too strict bound on deepseq

### ISSUE THREAD

**Issue by sternenseemann** [hadolint/hadolint#800]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior

hadolint can be built with GHC >= 9.0 and thus `deepseq` 1.4.5.0.

### Actual behavior

hadolint 2.9.1 (and master) has the following constraint: `deepseq ==1.4.4.*`. This should at least
be relaxed to `deepseq >= 1.4.4 && < 1.5` since minor releases (non breaking changes
as per PVP) shouldn't influence hadolint's ability to be built.

### Steps to reproduce the behavior

Build `hadolint` with GHC 9.0.2's default `deepseq` version 1.4.5.0.

**Comment by lorenzo** [comment]
thanks, will take care of this
