### ISSUE TITLE
bad error with docker tag latest-alpine

### ISSUE THREAD

**Issue by NPhMKgbDNy1M** [hadolint/hadolint#809]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

In the newest docker image (8h ago) with tag latest-alpine the hadolint file is copied to /hadolint instead to /bin/hadolint! With 2.9.3-alpine everything works.

docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/hadolint": stat /bin/hadolint: no such file or directory: unknown.

### Steps to reproduce the behavior

docker run --rm hadolint/hadolint:latest-alpine

docker run --rm hadolint/hadolint:latest-alpine hadolint --version

**Comment by NPhMKgbDNy1M** [comment]
please fix this fast.

**Comment by lorenzo** [comment]
this was already fixed yesterday. Thanks for reporting
