### ISSUE TITLE
2.10.0 is missing in DockerHub

### ISSUE THREAD

**Issue by sugarshin** [hadolint/hadolint#849]
- [ ] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

Hi, it seems to the latest release version is 2.10.0, but it's not available in DockerHub. Is there a plan to push 2.10.0 to DockerHub?

**Comment by offa** [comment]
You can use GHCR in the meantime: https://github.com/orgs/hadolint/packages/container/package/hadolint

**Comment by lclc** [comment]
@offa the problem with that is that it will probably run very quickly into the limit for pulling from outside of GitHub Actions (depending on the hadolint plan: https://github.com/features/packages#pricing)

**Comment by offa** [comment]
Are you sure those limitations apply to *public* repos too?

**Comment by lclc** [comment]
> Are you sure those limitations apply to _public_ repos too?

You are right. It says Private there. Sorry for the confusion.

**Comment by ahollmann** [comment]
Still the case: https://hub.docker.com/r/hadolint/hadolint/tags?page=1&name=2.10.0

I can only find 2.10-beta.

**Comment by lorenzo** [comment]
unfortunately I'm not able to retroactively fix it. There is a new version now that you can download
