### ISSUE TITLE
Add label org.opencontainers.image.source="https://github.com/hadolint/hadolint" to DOCKERFILE

### ISSUE THREAD

**Issue by marwin1991** [hadolint/hadolint#926]
Hello, for tools like renovate it is important to have define label `org.opencontainers.image.source`

So can we add label org.opencontainers.image.source="https://github.com/hadolint/hadolint" to DOCKERFILE ?

Base on this label, renovate will provide information about changes.

- https://docs.renovatebot.com/modules/datasource/docker/
- https://github.com/opencontainers/image-spec/blob/main/annotations.md

**Comment by lorenzo** [comment]
> I can create pull request with this change :)

Thanks

**Comment by marwin1991** [comment]
@lorenzo 

If you will have some free time you can check out !927
