### ISSUE TITLE
Simple Pre-commit configuration finds no files to scan.

### ISSUE THREAD

**Issue by balq60** [hadolint/hadolint#996]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint
    
That will find my Dockerfile and scan it
### Actual behavior
Reports nothing to scan, Skipped

### Steps to reproduce the behavior
1.  Create a Folder
2.  Copy pre-commit-config.yaml there
3.  Create a Dockerfile in the same folder
4.  Run pre-commit run -a
5.  Reports no files to scan

Admin:~/environment/Blue-Docker/v1/docker-sample (features/setup) $ pre-commit run -a
bandit...............................................(no files to check)Skipped
safety...............................................(no files to check)Skipped
Detect secrets...........................................................Passed
Lint Dockerfiles.....................................(no files to check)Skipped

**Additional environment details (OS, stack version, etc.)**
Running on Linux
Did a brew install
No complaints that it cannot be found
I have about 20 pre-commits configured and running, this new one will not find a Dockerfile even when it is sitting right there.

**Comment by mlubej** [comment]
@balq60 why is this closed? did you find a solution? Could you share it? I'm experiencing the same issues.

Thanks!

**Comment by balq60** [comment]
I had to add the file to git first, just like all other files, then it was scanned.  It is the catch-22 of pre-commits.
